"use client";

import { useEffect, useState } from "react";
import { RoleGate } from "@/components/auth/RoleGate";
import { RolePageShell } from "@/components/role/RolePageShell";

type Conflict = {
  id?: string;
  conflict_id?: string;
  conflict_type: string;
  description: string;
  severity: string;
  conflict_date?: string;
  is_resolved?: boolean;
};

export default function ConflictCentrePage() {
  const [conflicts, setConflicts] = useState<Conflict[]>([]);

  useEffect(() => {
    fetch("/api/conflicts").then((response) => response.json()).then((result) => setConflicts(result.data ?? []));
  }, []);

  return (
    <RolePageShell>
      <RoleGate allow={["ADMIN"]}>
        <section className="role-card">
          <div className="role-section-heading">
            <div><span className="role-kicker">Admin scheduling</span><h1>Conflict centre</h1><p>Room, faculty, cohort, and capacity warnings generated by the scheduling engine.</p></div>
            <span className="role-status error">{conflicts.filter((item) => !item.is_resolved).length} active</span>
          </div>
          <div className="conflict-centre-list">
            {conflicts.length === 0 && <div className="role-empty">No stored conflicts. Invalid timetable saves are still blocked immediately.</div>}
            {conflicts.map((conflict) => (
              <article key={conflict.conflict_id ?? conflict.id}>
                <span className={`role-status ${conflict.severity === "critical" ? "error" : "warning"}`}>{conflict.conflict_type.replaceAll("_", " ")}</span>
                <div><strong>{conflict.description}</strong><span>{conflict.conflict_date ?? "Current timetable"}</span></div>
              </article>
            ))}
          </div>
        </section>
      </RoleGate>
    </RolePageShell>
  );
}
